### ISSUE TITLE
Where should I download the corresponding game version?

### ISSUE THREAD

**Issue by freezing2688** [CS-NextClient/NextClient#16]
I only have the Steam version, it cannot start after installation
Tips Can't load cstrike\cl_dlls\client_mini.dll, But I am certain that the file exists
![11](https://github.com/user-attachments/assets/0b69792c-624f-4fee-807c-99e4bbab3947)

**Comment by freezing2688** [comment]
I have installed it, but when I turn off Steam and start it, the error still persists
![22](https://github.com/user-attachments/assets/65a57782-dc0a-4026-a709-9c7f07533cf5)

**Comment by Psycrow101** [comment]
@freezing2688 Are you on the "steam_legacy - Pre-25th Anniversary Build" beta branch on Steam?
![image](https://github.com/user-attachments/assets/bec2ea35-054c-4f7c-ac78-1f6593b108ea)
