### ISSUE TITLE
No steam support？

### ISSUE THREAD

**Issue by myheartwellgoon** [CS-NextClient/NextClient#17]
As title
Can you add no steam support?
Or does it support paid customization?

**Comment by Xelson** [comment]
This addon is intended only for a licensed copy of the game

**Comment by myheartwellgoon** [comment]
If you have to start steam, then there is no point



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年7月27日(星期六) 凌晨4:02
收件人: ***@***.***&gt;; 
抄送: "Ｍy ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [CS-NextClient/NextClient] No steam support？ (Issue #17)





 
This addon is intended only for a licensed copy of the game
 
&mdash;
