### ISSUE TITLE
Voice function implementation

### ISSUE THREAD

**Issue by rainbowsource** [CS-NextClient/NextClient#23]
Since version 6153, the voice function of the GoldSource engine has fully used the Steam API, which means that if the player is a pirated client, they will not be able to communicate using voice. Is it possible to implement a voice decoder that can also be used by pirated clients? Used with ReHLDS, it's just so delicious. Many thanks.

**Comment by Xelson** [comment]
Nextclient uses steam api to decode and encode the voice stream, just like the vanilla steam client does.
To connect steam players and pirates, it's better to use special server modules, such as [revoice](https://github.com/s1lentq/revoice)or [voicetranscoder](https://github.com/WPMGPRoSToTeMa/VoiceTranscoder)

**Comment by rainbowsource** [comment]
@Xelson I mean, what am I supposed to do if a player uses something like the Goldberg Emulator?

**Comment by Polarhigh** [comment]
You mean what if you install GoldbergEmu on NextClient? The voice functionality should still be implemented in the emulator itself 👀
