### ISSUE TITLE
Support Request for next_engine_mini.dll Error

### ISSUE THREAD

**Issue by IGNRexI** [CS-NextClient/NextClient#30]
I am encountering the following error:
Module next_engine_mini.dll not found

![image](https://github.com/user-attachments/assets/e248c545-e414-44e4-8118-c856e3387411)

Error Details:
The error message appears when I try to run the cs.exe file.
I have checked that my file and directory structure is correct, but the issue persists.

**Comment by Polarhigh** [comment]
Please note, NextClient is only compatible with steam version 8684. Other versions will not work.
https://github.com/CS-NextClient/NextClient?tab=readme-ov-file#installation
