### ISSUE TITLE
Add `KILLRARITY_INAIR` support

### ISSUE THREAD

**Issue by Xelson** [CS-NextClient/NextClient#5]
https://github.com/s1lentq/ReGameDLL_CS/commit/9f662645623fcafb2fbb6d840e13360edac27b2f#diff-672fbf226e2280aa8d2dc9884bee837facbb4b4cc9f84a9813e4d7b00650bf55R256

Expected result:
![Безымянный](https://github.com/CS-NextClient/NextClient/assets/43149567/c94ee742-3c5a-47dc-9e92-fa3e88c13b15)

Asset example, should be without the outline:
![inairkill](https://github.com/CS-NextClient/NextClient/assets/43149567/874576a0-28bf-421e-8e7f-e2f8785ace3d)

**Comment by Polarhigh** [comment]
Done in #11
