### ISSUE TITLE
Compatibility with wargods scanner

### ISSUE THREAD

**Issue by kovakovi2000** [CS-NextClient/NextClient#8]
The main executable is cs.exe and wargods only look for hl.exe, I'm sure that whatever functionality is in there could be implemented into another form, in a way that hl.exe stay the same.
Many server these days require you to make scan in order to play but if you say "I can't cus I have a fancy client" then they just going to ban you.
We all know that there's a server sided solution to check when ever the client is using NextClient or not. But if you want your client to be used then at the beginning this issue going to make it especially difficult.

All I say that resolve the scanning issue and if the scan result as "red" get in contact with the wargods creator to resolve it.

**Comment by Xelson** [comment]
You would just safely rename the executable `cs.exe` -> `cstrike.exe` this trick should allow you to run scans

**Comment by Polarhigh** [comment]
It will be renaIt will be renamed by default to cstrike.exemed by default to cstrike.exe
